import Head from "next/head";
import { Inter } from "@next/font/google";
import { useEffect, useMemo, useState } from "react";
import { User } from "domain/type/user";
import { Post } from "domain/type/post";
import { Comment } from "domain/type/comment";

import { ProgressSpinner } from "../components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [users, setUsers] = useState<User[]>([]);
  const [posts, setPosts] = useState<Post[]>([]);
  const [comments, setComments] = useState<Comment[]>([]);
  const [activeUser, setActiveUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [displayPostNumber, setDisplayPostNumber] = useState<number>(3);

  // https://jsonplaceholder.typicode.com/
  const getUsers = async () => {
    setIsLoading(true);
    const res = await fetch("https://jsonplaceholder.typicode.com/users");
    const data: User[] = await res.json();
    setUsers(data);
    setIsLoading(false);
  };

  const getPosts = async () => {
    setIsLoading(true);
    const res = await fetch(
      `https://jsonplaceholder.typicode.com/posts?userId=${activeUser?.id}`
    );
    const data: Post[] = await res.json();
    setPosts(data);
    setIsLoading(false);
  };

  const getComments = async (postId: number) => {
    setIsLoading(true);
    const res = await fetch(
      `https://jsonplaceholder.typicode.com/comments?postId=${postId}`
    );
    const data: Comment[] = await res.json();
    setComments(data);
    setIsLoading(false);
  };

  const filteredPosts = useMemo(() => {
    if (activeUser) {
      return posts
        .filter((post) => post.userId === activeUser.id)
        .slice(0, displayPostNumber);
    }
    return [];
  }, [activeUser, posts, displayPostNumber]);

  useEffect(() => {
    setDisplayPostNumber(3);
  }, [activeUser]);

  useEffect(() => {
    getUsers();
  }, []);

  useEffect(() => {
    if (activeUser) {
      getPosts();
    }
  }, [activeUser]);

  const expandPost = async (postId: number) => {
    await getComments(postId);
  };

  return (
    <>
      <Head>
        <title>User Post Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5">
        <h1 className="text-3xl font-bold mb-5">User Post Viewer</h1>
        <div className="mb-5">
          <h2 className="text-xl font-bold mb-2">
            Please select a user to find their posts
          </h2>
          <div className="flex flex-wrap">
            {users.map((user) => {
              return (
                <button
                  key={user.id}
                  className={`bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded-lg mr-2 mb-2 ${
                    user.id === activeUser?.id ? "bg-blue-500 text-white" : ""
                  }`}
                  onClick={() => setActiveUser(user)}
                >
                  {user.name.split(" ")[0]}
                </button>
              );
            })}
          </div>
        </div>
        {activeUser && (
          <div>
            <h2 className="text-xl font-bold mb-2">
              {activeUser.name}'s posts
            </h2>
            <div className="max-w-xl mx-auto">
              {filteredPosts.map((post) => {
                return (
                  <div
                    key={post.id}
                    className="bg-gray-100 p-4 mb-2 rounded-lg"
                  >
                    <h3 className="text-lg font-bold mb-1 text-black">
                      {post.title}
                    </h3>
                    <p className="text-gray-700">{post.body}</p>
                    <div className="mt-2">
                      <button
                        className="px-4 py-1 text-sm font-medium text-blue-600 rounded hover:bg-blue-600 hover:text-white"
                        onClick={() => expandPost(post.id)}
                      >
                        Expand
                      </button>
                    </div>
                    {comments.map((comment) => {
                      if (comment.postId === post.id) {
                        return (
                          <div
                            key={comment.id}
                            className="bg-gray-50 p-2 mt-2 rounded-lg"
                          >
                            <p className="text-gray-700 font-medium">
                              {comment.email}
                            </p>
                            <p className="text-gray-600">{comment.body}</p>
                          </div>
                        );
                      }
                    })}
                  </div>
                );
              })}
              {posts.length > 3 && displayPostNumber !== posts.length ? (
                <button
                  className="px-4 py-1 text-sm font-medium text-gray-200 rounded-lg hover:bg-gray-300 hover:text-gray-700"
                  onClick={() => {
                    setDisplayPostNumber(posts.length);
                  }}
                >
                  Load all
                </button>
              ) : null}
            </div>
          </div>
        )}
      </main>
      {isLoading ? (
        <div className={`fixed inset-0 z-50  `}>
          <div className="absolute inset-0 bg-gray-800 opacity-50"></div>
          <div className="flex items-center justify-center h-full">
            <ProgressSpinner size={4} />
          </div>
        </div>
      ) : null}
    </>
  );
}
